"""Exact finite observation-channel value for robust zero-error coding.

A source-law observation can help for two logically distinct reasons:

1. it can reveal information about which source law is active;
2. even when uninformative, a public random signal can coordinate randomized
   codebook selection.

This module keeps those effects separate. Nature chooses one law from a finite
rational scenario set. A public signal is generated by a declared rational
channel conditional on the scenario. The designer observes the signal and
selects a deterministic zero-error prefix codebook known to every decoder.

The bounded exact solver computes:

* deterministic no-signal minimax cost;
* shared-randomness no-signal minimax cost;
* deterministic signal-policy minimax cost;
* shared-randomness signal-policy minimax cost;
* perfect-scenario-information cost;
* the exact sensing-cost threshold relative to the shared-randomness baseline.

A shared-randomness signal policy is a mixture over complete deterministic
signal-to-codebook maps selected by a public seed independent of the source
scenario. Exact rational primal/dual zero-sum game certificates are reused.

If channel B is a garbling of channel A, A can simulate B and any policy built
on B. Consequently the shared-randomness minimax cost under A is no larger
than under B. This is a finite Blackwell-order statement for the declared
coding loss, not a universal scalar ranking of information channels.

All results are finite-scenario, one-shot, rational, bounded, and internal to
the declared observation/coding model. They are not evidence for simulation
and do not turn expected code length into parent-substrate hardware or physics.
"""

from __future__ import annotations

from dataclasses import dataclass
from fractions import Fraction
from itertools import product
from typing import Mapping, Sequence

from .confusion_graphs import ConfusionGraph
from .prior_weighted_codes import RationalInput, validate_rational_prior
from .robust_prior_codes import (
    ExactZeroSumGameCertificate,
    RobustCandidateEnumeration,
    RobustCodeCandidate,
    enumerate_robust_code_candidates,
    solve_exact_zero_sum_game,
)

ExactInput = RationalInput | Fraction | int
Distribution = tuple[Fraction, ...]
Matrix = tuple[tuple[Fraction, ...], ...]


def _fraction(value: ExactInput, *, name: str) -> Fraction:
    if isinstance(value, float):
        raise ValueError(f"{name} must be exact rational input")
    try:
        return value if isinstance(value, Fraction) else Fraction(value)
    except (TypeError, ValueError, ZeroDivisionError) as error:
        raise ValueError(f"invalid exact rational {name}") from error


def _validate_row_stochastic(
    matrix: Sequence[Sequence[ExactInput]],
    *,
    name: str,
) -> Matrix:
    rows = tuple(
        tuple(_fraction(value, name=f"{name} probability") for value in row)
        for row in matrix
    )
    if not rows or not rows[0]:
        raise ValueError(f"{name} matrix must be nonempty")
    width = len(rows[0])
    if any(len(row) != width for row in rows):
        raise ValueError(f"{name} matrix must be rectangular")
    if any(value < 0 for row in rows for value in row):
        raise ValueError(f"{name} probabilities must be nonnegative")
    if any(sum(row, Fraction(0)) != 1 for row in rows):
        raise ValueError(f"every {name} row must sum exactly to one")
    return rows


@dataclass(frozen=True)
class RationalObservationChannel:
    matrix: Matrix

    @property
    def scenario_count(self) -> int:
        return len(self.matrix)

    @property
    def signal_count(self) -> int:
        return len(self.matrix[0])

    @property
    def valid(self) -> bool:
        return (
            bool(self.matrix)
            and bool(self.matrix[0])
            and all(len(row) == self.signal_count for row in self.matrix)
            and all(value >= 0 for row in self.matrix for value in row)
            and all(sum(row, Fraction(0)) == 1 for row in self.matrix)
        )

    @classmethod
    def from_values(
        cls,
        matrix: Sequence[Sequence[ExactInput]],
    ) -> "RationalObservationChannel":
        result = cls(_validate_row_stochastic(matrix, name="observation channel"))
        if not result.valid:
            raise AssertionError("observation channel failed validation")
        return result


def identity_observation_channel(scenario_count: int) -> RationalObservationChannel:
    count = int(scenario_count)
    if count != scenario_count or count < 1:
        raise ValueError("scenario_count must be a positive integer")
    return RationalObservationChannel.from_values(
        tuple(
            tuple(Fraction(1) if row == column else Fraction(0) for column in range(count))
            for row in range(count)
        )
    )


def uninformative_observation_channel(
    scenario_count: int,
    signal_probabilities: Sequence[ExactInput],
) -> RationalObservationChannel:
    count = int(scenario_count)
    if count != scenario_count or count < 1:
        raise ValueError("scenario_count must be a positive integer")
    probabilities = tuple(
        _fraction(value, name="signal probability")
        for value in signal_probabilities
    )
    if not probabilities or any(value < 0 for value in probabilities):
        raise ValueError("signal probabilities must be nonempty and nonnegative")
    if sum(probabilities, Fraction(0)) != 1:
        raise ValueError("signal probabilities must sum exactly to one")
    return RationalObservationChannel(tuple(probabilities for _ in range(count)))


def symmetric_observation_channel(
    scenario_count: int,
    correct_probability: ExactInput,
) -> RationalObservationChannel:
    count = int(scenario_count)
    if count != scenario_count or count < 2:
        raise ValueError("symmetric channel requires at least two scenarios")
    correct = _fraction(correct_probability, name="correct_probability")
    if not 0 <= correct <= 1:
        raise ValueError("correct_probability must lie in [0,1]")
    incorrect = (Fraction(1) - correct) / (count - 1)
    return RationalObservationChannel.from_values(
        tuple(
            tuple(correct if row == column else incorrect for column in range(count))
            for row in range(count)
        )
    )


def garble_observation_channel(
    source: RationalObservationChannel,
    garbling_matrix: Sequence[Sequence[ExactInput]],
) -> RationalObservationChannel:
    """Return source-channel composition with a row-stochastic garbling kernel."""

    if not source.valid:
        raise ValueError("source observation channel must be valid")
    garbling = _validate_row_stochastic(garbling_matrix, name="garbling")
    if len(garbling) != source.signal_count:
        raise ValueError("one garbling row is required per source signal")
    output_count = len(garbling[0])
    matrix = tuple(
        tuple(
            sum(
                (
                    source.matrix[scenario][signal] * garbling[signal][output]
                    for signal in range(source.signal_count)
                ),
                Fraction(0),
            )
            for output in range(output_count)
        )
        for scenario in range(source.scenario_count)
    )
    return RationalObservationChannel(matrix)


@dataclass(frozen=True)
class ObservationPolicyCandidate:
    codes_by_signal: tuple[int, ...]
    scenario_costs: tuple[Fraction, ...]

    @property
    def signal_count(self) -> int:
        return len(self.codes_by_signal)


def _dominates_costs(
    left: Sequence[Fraction],
    right: Sequence[Fraction],
) -> bool:
    return (
        all(a <= b for a, b in zip(left, right))
        and any(a < b for a, b in zip(left, right))
    )


@dataclass(frozen=True)
class ObservationPolicyEnumeration:
    channel: RationalObservationChannel
    code_enumeration: RobustCandidateEnumeration
    policies: tuple[ObservationPolicyCandidate, ...]
    raw_policy_count: int
    distinct_cost_count: int
    dominated_count: int
    max_policies: int
    max_dominance_pairs: int

    @property
    def candidates(self) -> tuple[RobustCodeCandidate, ...]:
        return self.code_enumeration.candidates

    @property
    def valid(self) -> bool:
        if (
            not self.channel.valid
            or not self.code_enumeration.valid
            or self.channel.scenario_count != self.code_enumeration.scenario_count
            or not self.policies
            or self.raw_policy_count < self.distinct_cost_count
            or self.distinct_cost_count != len(self.policies) + self.dominated_count
            or len({policy.scenario_costs for policy in self.policies})
            != len(self.policies)
        ):
            return False
        for policy in self.policies:
            if (
                policy.signal_count != self.channel.signal_count
                or any(not 0 <= code < len(self.candidates) for code in policy.codes_by_signal)
                or policy.scenario_costs
                != _policy_scenario_costs(
                    self.channel,
                    self.candidates,
                    policy.codes_by_signal,
                )
            ):
                return False
        return not any(
            _dominates_costs(left.scenario_costs, right.scenario_costs)
            for left_index, left in enumerate(self.policies)
            for right_index, right in enumerate(self.policies)
            if left_index != right_index
        )


def _policy_scenario_costs(
    channel: RationalObservationChannel,
    candidates: Sequence[RobustCodeCandidate],
    codes_by_signal: Sequence[int],
) -> tuple[Fraction, ...]:
    if len(codes_by_signal) != channel.signal_count:
        raise ValueError("one code decision is required per signal")
    return tuple(
        sum(
            (
                channel.matrix[scenario][signal]
                * candidates[code].scenario_costs[scenario]
                for signal, code in enumerate(codes_by_signal)
            ),
            Fraction(0),
        )
        for scenario in range(channel.scenario_count)
    )


def enumerate_observation_policies(
    channel: RationalObservationChannel,
    code_enumeration: RobustCandidateEnumeration,
    *,
    max_policies: int = 500_000,
    max_dominance_pairs: int = 4_000_000,
) -> ObservationPolicyEnumeration:
    if not channel.valid or not code_enumeration.valid:
        raise ValueError("channel and code enumeration must be valid")
    if channel.scenario_count != code_enumeration.scenario_count:
        raise ValueError("channel rows and source-law scenarios differ")
    policy_cap = int(max_policies)
    pair_cap = int(max_dominance_pairs)
    if policy_cap < 1 or pair_cap < 1:
        raise ValueError("policy and dominance caps must be positive")
    code_count = len(code_enumeration.candidates)
    raw_count = code_count ** channel.signal_count
    if raw_count > policy_cap:
        raise ValueError("observation-policy space exceeds configured cap")

    by_cost: dict[tuple[Fraction, ...], ObservationPolicyCandidate] = {}
    for codes in product(range(code_count), repeat=channel.signal_count):
        costs = _policy_scenario_costs(channel, code_enumeration.candidates, codes)
        candidate = ObservationPolicyCandidate(tuple(codes), costs)
        incumbent = by_cost.get(costs)
        if incumbent is None or candidate.codes_by_signal < incumbent.codes_by_signal:
            by_cost[costs] = candidate

    distinct = tuple(by_cost.values())
    if len(distinct) * max(0, len(distinct) - 1) > pair_cap:
        raise ValueError("observation-policy dominance space exceeds configured cap")
    nondominated = tuple(
        sorted(
            (
                candidate
                for index, candidate in enumerate(distinct)
                if not any(
                    _dominates_costs(other.scenario_costs, candidate.scenario_costs)
                    for other_index, other in enumerate(distinct)
                    if other_index != index
                )
            ),
            key=lambda candidate: (
                candidate.scenario_costs,
                candidate.codes_by_signal,
            ),
        )
    )
    result = ObservationPolicyEnumeration(
        channel,
        code_enumeration,
        nondominated,
        raw_count,
        len(distinct),
        len(distinct) - len(nondominated),
        policy_cap,
        pair_cap,
    )
    if not result.valid:
        raise AssertionError("observation-policy enumeration failed validation")
    return result


def _scenario_by_action_matrix(
    costs_by_action: Sequence[Sequence[Fraction]],
) -> Matrix:
    columns = tuple(tuple(Fraction(value) for value in column) for column in costs_by_action)
    if not columns:
        raise ValueError("at least one action cost vector is required")
    scenario_count = len(columns[0])
    if scenario_count < 1 or any(len(column) != scenario_count for column in columns):
        raise ValueError("action cost vectors must have equal positive length")
    return tuple(
        tuple(columns[action][scenario] for action in range(len(columns)))
        for scenario in range(scenario_count)
    )


@dataclass(frozen=True)
class ObservationValueCertificate:
    graph: ConfusionGraph
    scenarios: tuple[Distribution, ...]
    channel: RationalObservationChannel
    code_enumeration: RobustCandidateEnumeration
    policy_enumeration: ObservationPolicyEnumeration
    deterministic_no_signal_value: Fraction
    deterministic_no_signal_code: int
    shared_no_signal_game: ExactZeroSumGameCertificate
    deterministic_observation_value: Fraction
    deterministic_observation_policy: ObservationPolicyCandidate
    shared_observation_game: ExactZeroSumGameCertificate
    perfect_information_value: Fraction
    perfect_codes: tuple[int, ...]

    @property
    def shared_no_signal_value(self) -> Fraction:
        return self.shared_no_signal_game.value

    @property
    def shared_observation_value(self) -> Fraction:
        return self.shared_observation_game.value

    @property
    def randomization_value_without_information(self) -> Fraction:
        return self.deterministic_no_signal_value - self.shared_no_signal_value

    @property
    def information_value_over_shared_randomness(self) -> Fraction:
        return self.shared_no_signal_value - self.shared_observation_value

    @property
    def deterministic_signal_value(self) -> Fraction:
        return self.deterministic_no_signal_value - self.deterministic_observation_value

    @property
    def perfect_information_value_over_shared_randomness(self) -> Fraction:
        return self.shared_no_signal_value - self.perfect_information_value

    @property
    def sensing_cost_threshold(self) -> Fraction:
        return self.information_value_over_shared_randomness

    @property
    def valid(self) -> bool:
        candidates = self.code_enumeration.candidates
        policies = self.policy_enumeration.policies
        if (
            not self.channel.valid
            or not self.code_enumeration.valid
            or not self.policy_enumeration.valid
            or self.policy_enumeration.channel != self.channel
            or self.policy_enumeration.code_enumeration != self.code_enumeration
            or self.code_enumeration.graph != self.graph
            or self.scenarios != self.code_enumeration.priors
            or self.channel.scenario_count != len(self.scenarios)
            or not self.shared_no_signal_game.valid
            or not self.shared_observation_game.valid
            or not 0 <= self.deterministic_no_signal_code < len(candidates)
            or self.deterministic_observation_policy not in policies
            or len(self.perfect_codes) != len(self.scenarios)
        ):
            return False
        code_matrix = _scenario_by_action_matrix(
            tuple(candidate.scenario_costs for candidate in candidates)
        )
        policy_matrix = _scenario_by_action_matrix(
            tuple(policy.scenario_costs for policy in policies)
        )
        deterministic_code_values = tuple(max(column) for column in zip(*code_matrix))
        deterministic_policy_values = tuple(
            max(column) for column in zip(*policy_matrix)
        )
        perfect_codes = tuple(
            min(
                range(len(candidates)),
                key=lambda code: (
                    candidates[code].scenario_costs[scenario],
                    code,
                ),
            )
            for scenario in range(len(self.scenarios))
        )
        perfect = max(
            candidates[code].scenario_costs[scenario]
            for scenario, code in enumerate(perfect_codes)
        )
        return (
            self.shared_no_signal_game.cost_matrix == code_matrix
            and self.shared_observation_game.cost_matrix == policy_matrix
            and self.deterministic_no_signal_value == min(deterministic_code_values)
            and deterministic_code_values[self.deterministic_no_signal_code]
            == self.deterministic_no_signal_value
            and self.deterministic_observation_value
            == min(deterministic_policy_values)
            and max(self.deterministic_observation_policy.scenario_costs)
            == self.deterministic_observation_value
            and self.perfect_codes == perfect_codes
            and self.perfect_information_value == perfect
            and self.perfect_information_value
            <= self.shared_observation_value
            <= self.shared_no_signal_value
            <= self.deterministic_no_signal_value
            and self.shared_observation_value
            <= self.deterministic_observation_value
            <= self.deterministic_no_signal_value
            and self.randomization_value_without_information >= 0
            and self.information_value_over_shared_randomness >= 0
        )


def exact_observation_channel_value(
    graph: ConfusionGraph,
    source_law_scenarios: Sequence[
        Sequence[ExactInput] | Mapping[object, ExactInput]
    ],
    channel: RationalObservationChannel,
    *,
    max_vertices: int = 8,
    max_partitions: int = 250_000,
    max_candidates: int = 500_000,
    max_prefix_assignments: int = 10_000_000,
    max_prefix_shapes: int = 100_000,
    max_code_dominance_pairs: int = 4_000_000,
    max_policies: int = 500_000,
    max_policy_dominance_pairs: int = 4_000_000,
    max_game_bases: int = 2_000_000,
) -> ObservationValueCertificate:
    """Solve deterministic and shared-randomness observation-channel games."""

    supplied = tuple(source_law_scenarios)
    if not supplied:
        raise ValueError("at least one source-law scenario is required")
    scenarios = tuple(validate_rational_prior(graph, scenario) for scenario in supplied)
    if not channel.valid or channel.scenario_count != len(scenarios):
        raise ValueError("channel rows must match source-law scenarios")

    enumeration = enumerate_robust_code_candidates(
        graph,
        scenarios,
        max_vertices=max_vertices,
        max_partitions=max_partitions,
        max_candidates=max_candidates,
        max_prefix_assignments=max_prefix_assignments,
        max_prefix_shapes=max_prefix_shapes,
        max_dominance_pairs=max_code_dominance_pairs,
    )
    policies = enumerate_observation_policies(
        channel,
        enumeration,
        max_policies=max_policies,
        max_dominance_pairs=max_policy_dominance_pairs,
    )
    candidates = enumeration.candidates

    code_matrix = _scenario_by_action_matrix(
        tuple(candidate.scenario_costs for candidate in candidates)
    )
    policy_matrix = _scenario_by_action_matrix(
        tuple(policy.scenario_costs for policy in policies.policies)
    )
    deterministic_code_values = tuple(max(column) for column in zip(*code_matrix))
    deterministic_code = min(
        range(len(candidates)),
        key=lambda code: (
            deterministic_code_values[code],
            code,
        ),
    )
    deterministic_policy_values = tuple(
        max(column) for column in zip(*policy_matrix)
    )
    deterministic_policy = min(
        range(len(policies.policies)),
        key=lambda policy: (
            deterministic_policy_values[policy],
            policies.policies[policy].codes_by_signal,
        ),
    )
    perfect_codes = tuple(
        min(
            range(len(candidates)),
            key=lambda code: (
                candidates[code].scenario_costs[scenario],
                code,
            ),
        )
        for scenario in range(len(scenarios))
    )
    perfect_value = max(
        candidates[code].scenario_costs[scenario]
        for scenario, code in enumerate(perfect_codes)
    )
    result = ObservationValueCertificate(
        graph,
        scenarios,
        channel,
        enumeration,
        policies,
        deterministic_code_values[deterministic_code],
        deterministic_code,
        solve_exact_zero_sum_game(code_matrix, max_bases=max_game_bases),
        deterministic_policy_values[deterministic_policy],
        policies.policies[deterministic_policy],
        solve_exact_zero_sum_game(policy_matrix, max_bases=max_game_bases),
        perfect_value,
        perfect_codes,
    )
    if not result.valid:
        raise AssertionError("observation-channel value certificate failed")
    return result


@dataclass(frozen=True)
class SensingDecisionCertificate:
    baseline_shared_value: Fraction
    observation_shared_value: Fraction
    sensing_cost: Fraction
    threshold: Fraction
    use_observation: bool
    optimal_total_value: Fraction

    @property
    def valid(self) -> bool:
        return (
            self.threshold
            == self.baseline_shared_value - self.observation_shared_value
            and self.threshold >= 0
            and self.sensing_cost >= 0
            and self.use_observation
            == (
                self.observation_shared_value + self.sensing_cost
                < self.baseline_shared_value
            )
            and self.optimal_total_value
            == min(
                self.baseline_shared_value,
                self.observation_shared_value + self.sensing_cost,
            )
        )


def exact_sensing_decision(
    certificate: ObservationValueCertificate,
    sensing_cost: ExactInput,
) -> SensingDecisionCertificate:
    if not certificate.valid:
        raise ValueError("observation value certificate must be valid")
    cost = _fraction(sensing_cost, name="sensing_cost")
    if cost < 0:
        raise ValueError("sensing_cost must be nonnegative")
    result = SensingDecisionCertificate(
        certificate.shared_no_signal_value,
        certificate.shared_observation_value,
        cost,
        certificate.sensing_cost_threshold,
        certificate.shared_observation_value + cost
        < certificate.shared_no_signal_value,
        min(
            certificate.shared_no_signal_value,
            certificate.shared_observation_value + cost,
        ),
    )
    if not result.valid:
        raise AssertionError("sensing decision failed validation")
    return result


@dataclass(frozen=True)
class BlackwellComparisonCertificate:
    informative_channel: RationalObservationChannel
    garbling_matrix: Matrix
    garbled_channel: RationalObservationChannel
    informative_value: ObservationValueCertificate
    garbled_value: ObservationValueCertificate

    @property
    def value_improvement(self) -> Fraction:
        return (
            self.garbled_value.shared_observation_value
            - self.informative_value.shared_observation_value
        )

    @property
    def valid(self) -> bool:
        return (
            self.informative_channel.valid
            and self.garbled_channel.valid
            and self.informative_value.valid
            and self.garbled_value.valid
            and self.informative_value.graph == self.garbled_value.graph
            and self.informative_value.scenarios == self.garbled_value.scenarios
            and garble_observation_channel(
                self.informative_channel,
                self.garbling_matrix,
            )
            == self.garbled_channel
            and self.informative_value.shared_observation_value
            <= self.garbled_value.shared_observation_value
            and self.value_improvement >= 0
        )


def exact_blackwell_comparison(
    graph: ConfusionGraph,
    source_law_scenarios: Sequence[
        Sequence[ExactInput] | Mapping[object, ExactInput]
    ],
    informative_channel: RationalObservationChannel,
    garbling_matrix: Sequence[Sequence[ExactInput]],
    **solver_kwargs: object,
) -> BlackwellComparisonCertificate:
    garbling = _validate_row_stochastic(garbling_matrix, name="garbling")
    garbled = garble_observation_channel(informative_channel, garbling)
    informative_value = exact_observation_channel_value(
        graph,
        source_law_scenarios,
        informative_channel,
        **solver_kwargs,
    )
    garbled_value = exact_observation_channel_value(
        graph,
        source_law_scenarios,
        garbled,
        **solver_kwargs,
    )
    result = BlackwellComparisonCertificate(
        informative_channel,
        garbling,
        garbled,
        informative_value,
        garbled_value,
    )
    if not result.valid:
        raise AssertionError("Blackwell comparison certificate failed")
    return result


def symmetric_heavy_source_laws(
    scenario_count: int,
    heavy_probability: ExactInput,
) -> tuple[Distribution, ...]:
    count = int(scenario_count)
    if count != scenario_count or count < 2:
        raise ValueError("scenario_count must be an integer at least two")
    heavy = _fraction(heavy_probability, name="heavy_probability")
    if not Fraction(1, count) <= heavy <= 1:
        raise ValueError(
            "heavy_probability must lie between uniform mass and one"
        )
    light = (Fraction(1) - heavy) / (count - 1)
    return tuple(
        tuple(heavy if scenario == state else light for state in range(count))
        for scenario in range(count)
    )
